apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

---

apiVersion: v1
kind: Service
metadata:
  name: counter-service
  labels:
    app: counter-service
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: counter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: counter
spec:
  serviceName: counter-service
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-central1-a
                  - key: failure-domain.beta.kubernetes.io/region
                    operator: In
                    values:
                      - us-central1
      containers:
        - name: counter
          image: "kahootali/counter:1.0"
          volumeMounts:
            - name: pvc-stateful
              mountPath: /app/
  volumeClaimTemplates:
    - metadata:
        name: pvc-stateful
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
