apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-app
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      name: daemon-app
      labels:
        app: daemon
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "devs"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                      - devs
      containers:
        - name: just-container
          image: supergiantkir/animals:bear
