#username=$(echo -n "admin" | base64)
#password=$(echo -n "kabilanmani" | base64)
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  username: YWRtaW4=
  password: a2FiaWxhbm1hbmk=
