apiVersion: v1
kind: Pod
metadata:
  name: test-gce
spec:
  volumes:
    - name: test-volume
      # This AWS EBS volume must already exist.
      #awsElasticBlockStore:
      #  volumeID: "<volume id>"
      #  fsType: ext4
      # This GCE PD must already exist.
      gcePersistentDisk:
        pdName: my-data-disk
        fsType: ext4
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      volumeMounts:
        - mountPath: /test-ebs
          name: test-volume



#https://cloud.google.com/compute/docs/disks/repd-failover