apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: votingapp-ingress
spec:
  rules:
   - http:
      paths:
        - path: /vote
          backend:
            serviceName: result-service
            servicePort: 8080
        - path: /result
          backend:
            serviceName: voting-service
            servicePort: 8080


#