#https://github.com/kubernetes/ingress-nginx/blob/faf80ad89a1e49113cc9791f0137e2f5a542487a/controllers/nginx/configuration.md#rewrite
#https://stackoverflow.com/questions/61541812/ingress-nginx-how-to-serve-assets-to-application
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: votingapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 35.222.22.152.xip.io
    http:
      paths:
        - path: /
          backend:
            serviceName: result-service
            servicePort: 80
        - path: /vote
          backend:
            serviceName: voting-service
            servicePort: 80
    
