apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  namespace: retail-vrp-inventory-allocator
  labels:
    name: myapp-deploy
    app: myapp
    version: v2.0.0
spec:
  replicas: 8
  selector:
    matchLabels:
      name: myapp-pod
      app: myapp
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp-pod
        app: myapp
        version: v2.0.0
    spec:
      containers:
        - name: myapp
          image: deekshithsn/k8s-deployment-strategies
          ports:
            - name: http
              containerPort: 8080
            - name: probe
              containerPort: 8086
          env:
            - name: VERSION
              value: v2.0.0
          resources:
            limits:
              cpu: 1500m
              memory: 3302.7Mi
            requests:
              cpu: 1500m
              memory: 3302.7Mi        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
