apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: retail-vrp-rbg-ch-nfr-pdb
  namespace: retail-vrp-rbg
spec:
  minAvailable: "90%"  
  selector:
    matchLabels:
      app: retail-vrp-rbg-ch-nfr-playground