apiVersion: v1
kind: Service
metadata:
  name: clusterip-backendservice
  labels:
    app: myapp-service-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: myapp-httpd

