apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-service
  labels:
    app: myapp-service-httpd
    tier: frontend
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: myapp-httpd

