apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-service
  labels:
    app: myapp-service-httpd
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 10010
      targetPort: 3000
      nodePort: 37001
  selector:
    app: myapp-httpd

