apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-deployment
  labels:
    app: resultapp
    tier: frontent
spec:
  replicas: 5
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      affinity:
        nodeAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: Disktype
                    operator: In
                    values:
                      - ssd
                  - key: Memory
                    operator: Gt
                    values:
                      - "10"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: Cpu
                    operator: In
                    values:
                      - High
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: https://localhost
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1