# Default values for VotingCharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationName: VotingApp

applications:
  voteapp: 
    name: voteui
    image:
      repository: kabilanmani
      imagename: votecode
      tag: 5
      pullPolicy: IfNotPresent      
    imageName: kabilanmani/votecode:5    
    service:
      Type: NodePort
      containerPort: 80
      targetPort: 80
      NodePort: 30004
    probes:
      path: /vote/
      port: 80 
    replicationcount: 1
  resultapp: 
    name: resultui
    imageName: kodekloud/examplevotingapp_result:v1
    image:
      repository: kodekloud
      imagename: examplevotingapp_result
      tag: v1
      pullPolicy: IfNotPresent         
    service:
      Type: NodePort
      containerPort: 80
      targetPort: 80
      NodePort: 30005
    probes:
      path: /
      port: 80 
    replicationcount: 1
  workerapp: 
    name: worker
    image:
      repository: kodekloud
      imagename: examplevotingapp_worker
      tag: v1
      pullPolicy: IfNotPresent      
    imageName: kodekloud/examplevotingapp_worker:v1    
    service:
    probes:
    replicationcount: 1
  redisapp: 
    name: redis
    imageName: redis
    image:
      imagename: redis
      tag: latest
      pullPolicy: IfNotPresent         
    service:
      Type: ClusterIP
      containerPort: 6379
      targetPort: 6379
      NodePort: 30006
    probes:
    replicationcount: 1  
  postgressapp: 
    name: postgress
    imageName: postgres  
    image:
      imagename: postgres
      tag: latest
      pullPolicy: IfNotPresent       
    service:
      Type: ClusterIP
      containerPort: 5432
      targetPort: 5432
      NodePort: 30007
    probes:
    replicationcount: 1    

initialDelaySeconds: 5
periodSeconds: 5
successThreshold: 1
failureThreshold: 3
timeoutSeconds: 1 



replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
