apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    tier: frontend
spec:
  template:
    metadata:
      name: myapp-pod-nginx
      labels:
        app: myapp-nginx
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3

#kubectl create -f ReplicationController.yml
#kubectl get nodes
#kubectl get replicationcontroller





