#https://dev.to/kaoskater08/building-a-headless-service-in-kubernetes-3bk8
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: eddiehale/hellonodeapi
          ports:
            - containerPort: 3000
 #kubectl run -i --tty --image busybox:1.28 dns-test --restart=Never --rm
              #nslookup servicename